(define (domain question5b)
  (:requirements :typing :action-costs :equality :conditional-effects :negative-preconditions :disjunctive-preconditions)
  (:predicates
    (InRoomA)
    (InRoomB)
    (InRoomC)
    (KeyInRoomA)
    (KeyInRoomB)
    (KeyInRoomC)
    (Holding)
    (YHolding) ; representing "Y(Holding)"
  )
  (:action move
      :parameters ()
      :precondition (or (InRoomA)
                        (and (InRoomB)
                             (Holding)
                             (not (YHolding))))
      :effect (and (when (and (InRoomA)
                              (not (Holding)))
                         (and (InRoomB)
                              (not (InRoomA))
                              (not (YHolding))))
                   (when (and (InRoomA)
                              (Holding))
                        (and (InRoomB)
                             (KeyInRoomB)
                             (YHolding)
                             (not (InRoomA))
                             (not (KeyInRoomA)))) 
                   (when (and (InRoomB)
                              (Holding)
                              (not (YHolding)))
                        (and (InRoomC)
                             (KeyInRoomC)
                             (YHolding)
                             (not (InRoomB))
                             (not (KeyInRoomB)))))
  )
  (:action pickup
      :parameters ()
      :precondition (and (not (Holding))
                         (or (and (KeyInRoomA)
                                  (InRoomA))
                             (and (KeyInRoomB)
                                  (InRoomB))))
      :effect (and (Holding)
                   (not (YHolding)))
  )
)
  